# account-service\kubernetes\secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: account-service-secrets
type: Opaque
data:
  # Base64 encoded secrets
  DB_USER: cG9zdGdyZXM=  # postgres
  DB_PASSWORD: c2VjdXJlX3Bhc3N3b3JkX2hlcmU=  # secure_password_here
  REDIS_PASSWORD: c2VjdXJlX3JlZGlzX3Bhc3N3b3JkX2hlcmU=  # secure_redis_password_here
  JWT_SECRET: c2VjdXJlX2p3dF9zZWNyZXRfa2V5X2hlcmU=  # secure_jwt_secret_key_here
  API_KEY: c2VjdXJlX2FwaV9rZXlfaGVyZQ==  # secure_api_key_here
