# File: backend/services/account-service/deployments/kubernetes/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: platform
  labels:
    app: account-service
    component: backend
    part-of: russian-steam
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  - port: 9090
    targetPort: grpc
    protocol: TCP
    name: grpc
  selector:
    app: account-service
