groups:
- name: auth-service-alerts
  rules:
  - alert: AuthServiceDown
    expr: up{job="auth-service"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Auth Service is down"
      description: "Auth Service has been down for more than 1 minute."
      runbook_url: "https://wiki.gaiming.ru/runbooks/auth-service-down"

  - alert: AuthServiceHighErrorRate
    expr: sum(rate(http_requests_total{job="auth-service", status_code=~"5.."}[5m])) / sum(rate(http_requests_total{job="auth-service"}[5m])) > 0.05
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Auth Service has high error rate"
      description: "Auth Service error rate is above 5% for more than 5 minutes (current value: {{ $value | humanizePercentage }})."
      runbook_url: "https://wiki.gaiming.ru/runbooks/auth-service-high-error-rate"

  - alert: AuthServiceHighLatency
    expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job="auth-service"}[5m])) by (le)) > 0.5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Auth Service has high latency"
      description: "Auth Service 95th percentile latency is above 500ms for more than 5 minutes (current value: {{ $value | humanizeDuration }})."
      runbook_url: "https://wiki.gaiming.ru/runbooks/auth-service-high-latency"

  - alert: AuthServiceHighCPUUsage
    expr: sum(rate(container_cpu_usage_seconds_total{container="auth-service"}[5m])) / sum(container_spec_cpu_quota{container="auth-service"} / 100000) > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Auth Service has high CPU usage"
      description: "Auth Service is using more than 80% of its CPU quota for more than 5 minutes (current value: {{ $value | humanizePercentage }})."
      runbook_url: "https://wiki.gaiming.ru/runbooks/auth-service-high-cpu-usage"

  - alert: AuthServiceHighMemoryUsage
    expr: sum(container_memory_usage_bytes{container="auth-service"}) / sum(container_spec_memory_limit_bytes{container="auth-service"}) > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Auth Service has high memory usage"
      description: "Auth Service is using more than 80% of its memory quota for more than 5 minutes (current value: {{ $value | humanizePercentage }})."
      runbook_url: "https://wiki.gaiming.ru/runbooks/auth-service-high-memory-usage"

  - alert: AuthServiceRestarting
    expr: changes(kube_pod_container_status_restarts_total{container="auth-service"}[15m]) > 3
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Auth Service is restarting frequently"
      description: "Auth Service has restarted more than 3 times in the last 15 minutes."
      runbook_url: "https://wiki.gaiming.ru/runbooks/auth-service-restarting"

  - alert: AuthServiceHighLoginFailureRate
    expr: sum(rate(auth_login_failures_total{job="auth-service"}[5m])) / sum(rate(auth_login_attempts_total{job="auth-service"}[5m])) > 0.3
    for: 15m
    labels:
      severity: warning
    annotations:
      summary: "Auth Service has high login failure rate"
      description: "Auth Service login failure rate is above 30% for more than 15 minutes (current value: {{ $value | humanizePercentage }})."
      runbook_url: "https://wiki.gaiming.ru/runbooks/auth-service-high-login-failure-rate"

  - alert: AuthServiceDatabaseConnectionFailures
    expr: rate(auth_database_connection_failures_total{job="auth-service"}[5m]) > 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Auth Service has database connection failures"
      description: "Auth Service is experiencing database connection failures for more than 5 minutes."
      runbook_url: "https://wiki.gaiming.ru/runbooks/auth-service-database-connection-failures"

  - alert: AuthServiceRedisConnectionFailures
    expr: rate(auth_redis_connection_failures_total{job="auth-service"}[5m]) > 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Auth Service has Redis connection failures"
      description: "Auth Service is experiencing Redis connection failures for more than 5 minutes."
      runbook_url: "https://wiki.gaiming.ru/runbooks/auth-service-redis-connection-failures"

  - alert: AuthServiceKafkaConnectionFailures
    expr: rate(auth_kafka_connection_failures_total{job="auth-service"}[5m]) > 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Auth Service has Kafka connection failures"
      description: "Auth Service is experiencing Kafka connection failures for more than 5 minutes."
      runbook_url: "https://wiki.gaiming.ru/runbooks/auth-service-kafka-connection-failures"

  - alert: AuthServiceTooManyPendingTokens
    expr: auth_pending_tokens_count{job="auth-service"} > 10000
    for: 15m
    labels:
      severity: warning
    annotations:
      summary: "Auth Service has too many pending tokens"
      description: "Auth Service has more than 10,000 pending tokens for more than 15 minutes (current value: {{ $value }})."
      runbook_url: "https://wiki.gaiming.ru/runbooks/auth-service-too-many-pending-tokens"

  - alert: AuthServiceGrpcHighErrorRate
    expr: sum(rate(auth_service_grpc_responses_total{job="auth-service", grpc_code!~"OK|ALREADY_EXISTS|NOT_FOUND"}[5m])) / sum(rate(auth_service_grpc_requests_total{job="auth-service"}[5m])) > 0.05
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Auth Service has high gRPC error rate"
      description: "Auth Service gRPC error rate (excluding OK, AlreadyExists, NotFound) is above 5% for more than 5 minutes (current value: {{ $value | humanizePercentage }})."
      runbook_url: "https://wiki.gaiming.ru/runbooks/auth-service-grpc-high-error-rate"

  - alert: AuthServiceGrpcHighLatency
    expr: histogram_quantile(0.95, sum(rate(auth_service_grpc_request_duration_seconds_bucket{job="auth-service"}[5m])) by (le)) > 0.5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Auth Service has high gRPC latency"
      description: "Auth Service 95th percentile gRPC latency is above 500ms for more than 5 minutes (current value: {{ $value | humanizeDuration }})."
      runbook_url: "https://wiki.gaiming.ru/runbooks/auth-service-grpc-high-latency"

  - alert: AuthServiceHigh2FAFailureRate
    expr: sum(rate(auth_service_2fa_verification_attempts_total{job="auth-service", status=~"failure_login_invalid_code|failure_activation_invalid_code"}[5m])) / sum(rate(auth_service_2fa_verification_attempts_total{job="auth-service"}[5m])) > 0.2
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Auth Service has high 2FA failure rate"
      description: "Auth Service 2FA failure rate is above 20% for more than 10 minutes (current value: {{ $value | humanizePercentage }})."
      runbook_url: "https://wiki.gaiming.ru/runbooks/auth-service-high-2fa-failure-rate"

  - alert: AuthServiceHighDetailedLoginFailureRate
    expr: sum(rate(auth_service_login_attempts_total{job="auth-service", status=~"failure_credentials|failure_user_not_found"}[5m])) / sum(rate(auth_service_login_attempts_total{job="auth-service"}[5m])) > 0.3
    for: 15m
    labels:
      severity: warning
    annotations:
      summary: "Auth Service has high detailed login failure rate (credentials/user_not_found)"
      description: "Auth Service login failure rate for bad credentials or user not found is above 30% for more than 15 minutes (current value: {{ $value | humanizePercentage }})."
      runbook_url: "https://wiki.gaiming.ru/runbooks/auth-service-high-login-failure-rate"

  - alert: AuthServiceHighAccountLockoutRate
    expr: sum(rate(auth_service_login_attempts_total{job="auth-service", status="failure_account_locked"}[10m])) > 1
    for: 5m # Alert if more than 1 lockout per minute on average over 10 mins
    labels:
      severity: critical
    annotations:
      summary: "Auth Service has a high rate of account lockouts"
      description: "Auth Service is locking out more than 1 account per minute on average over the last 10 minutes (current rate: {{ $value }} lockouts/min)."
      runbook_url: "https://wiki.gaiming.ru/runbooks/auth-service-high-account-lockout-rate"
