package models

import (
	"time"

	"github.com/google/uuid"
)

// VerificationCodeType defines the purpose of a verification code.
type VerificationCodeType string

const (
	VerificationCodeTypeEmailVerification      VerificationCodeType = "email_verification"
	VerificationCodeTypePasswordReset        VerificationCodeType = "password_reset"
	VerificationCodeTypeMFADeviceVerification VerificationCodeType = "mfa_device_verification"
	// Add other types as needed
)

// VerificationCode represents a temporary code used for various verification processes.
// Aligned with the 'verification_codes' table in auth_data_model.md.
type VerificationCode struct {
	ID        uuid.UUID            `json:"id" db:"id"`
	UserID    uuid.UUID            `json:"user_id" db:"user_id"`
	Type      VerificationCodeType `json:"type" db:"type"`
	CodeHash  string               `json:"-" db:"code_hash"` // Hash of the code
	ExpiresAt time.Time            `json:"expires_at" db:"expires_at"`
	CreatedAt time.Time            `json:"created_at" db:"created_at"` // Handled by DB default
	UsedAt    *time.Time           `json:"used_at,omitempty" db:"used_at"`
}

// CreateVerificationCodeRequest contains data for creating a new verification code.
type CreateVerificationCodeRequest struct {
	UserID    uuid.UUID
	Type      VerificationCodeType
	CodeHash  string // Hash of the code, generated by service
	ExpiresAt time.Time
}
