# File: backend/services/auth-service/deployments/helm/auth-service/values-secrets-template.yaml
# Template for production secrets. Replace values with real credentials.

secrets:
  dbPassword: ""
  redisPassword: ""
  jwtSecret: ""
  kafkaUsername: ""
  kafkaPassword: ""
  telegramBotToken: ""
  vaultToken: ""
  serviceApiKey: ""
