# File: backend/services/account-service/deployments/monitoring/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'account-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['account-service:8080']
        labels:
          service: 'account-service'
          environment: 'development'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
          environment: 'development'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-metrics'
          environment: 'development'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'container-metrics'
          environment: 'development'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - 'alertmanager:9093'

rule_files:
  # - "alert_rules.yml"
